@startuml
!pragma teoz true

== Release ==
participant "Dev branch" as devbranch order 10 #LightBlue
participant "Release branch" as rlsbranch order 20 #YellowGreen
participant "Master branch" as master order 30 #99FF99
participant "Hotfix branch" as hotbranch order 40 #DarkSalmon

{startrc} devbranch -> rlsbranch ++ #YellowGreen: Create branch release_x.y.0


note left of devbranch
  Evolutions
end note


rlsbranch <- devbranch: Merge bug fixes
rlsbranch <- devbranch: Merge more bug fixes


note right of rlsbranch
  - Bug fixes
end note


rlsbranch -> master: Merge
note right of master
    Official release
    - Tag "x.y.0"
    - Push to DockerHub
end note

{endrc} rlsbranch --> devbranch --: Release done

devbranch -> rlsbranch: Start release x.(y+1).0
note left of devbranch
  Increase x if case of
  major breaking change
end note


... ...
{startrc} <-> {endrc}: 4-8 weeks

== Hotfix ==

master -> hotbranch ++ #DarkSalmon: Create short-lived fix branch x.y.1

note left of devbranch
    Severe bug fixed
end note

hotbranch <- devbranch --: Merge hotfix
hotbranch --> master: Merge
note right of master
    Official release
    - Tag "x.y.1"
    - Deploy to DockerHub
end note
hotbranch --> rlsbranch: Merge

@enduml